// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DiggerFlight.PcnAcnCalculator.Test
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CheckForInvalidInfrastructreFeature : object, Xunit.IClassFixture<CheckForInvalidInfrastructreFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "CheckForInvalidInfrastructre", "\tAs an MSFS user and AI Air Trafic Control User\r\n\tI Want Air Trafic Control to kn" +
                "ow what Infrastructure is invalid for my aircraft type\r\n\tSo that I don\'t receive" +
                " taxi requests via invalid areas similarly to the real world, unless data is mis" +
                "sing", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CheckForInvalidInfrastructre.feature"
#line hidden
        
        public CheckForInvalidInfrastructreFeature(CheckForInvalidInfrastructreFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Check For Invalid Taxiways only when valid data is available")]
        [Xunit.TraitAttribute("FeatureTitle", "CheckForInvalidInfrastructre")]
        [Xunit.TraitAttribute("Description", "Check For Invalid Taxiways only when valid data is available")]
        [Xunit.InlineDataAttribute("Valid data", "A320", "EGNJ", "44000kgs", "TAXI_B,TAXI_E,TAXI_G,TAXI_H", new string[0])]
        [Xunit.InlineDataAttribute("Valid data", "A320", "EGNJ", "44000kg", "TAXI_B,TAXI_E,TAXI_G,TAXI_H", new string[0])]
        [Xunit.InlineDataAttribute("Valid data", "A320", "EGNJ", "97000lbs", "TAXI_B,TAXI_E,TAXI_G,TAXI_H", new string[0])]
        [Xunit.InlineDataAttribute("Valid data", "A320", "EGNJ", "88000lb", "TAXI_E,TAXI_G,TAXI_H", new string[0])]
        [Xunit.InlineDataAttribute("Valid data no invalid Taxiways", "C152", "EGNJ", "2499kgs", "", new string[0])]
        [Xunit.InlineDataAttribute("Valid data invalid Taxiways", "C152", "EGNJ", "2501kgs", "TAXI_G,TAXI_H", new string[0])]
        [Xunit.InlineDataAttribute("Invalid data - aircraft", "B747", "EGNJ", "44000kgs", "", new string[0])]
        [Xunit.InlineDataAttribute("Invalid data - airfield", "A320", "EGKK", "44000kgs", "", new string[0])]
        [Xunit.InlineDataAttribute("Invalid data - weight", "A320", "EGNJ", "", "", new string[0])]
        [Xunit.InlineDataAttribute("Invalid data - all", "B747", "EGKK", "", "", new string[0])]
        public async System.Threading.Tasks.Task CheckForInvalidTaxiwaysOnlyWhenValidDataIsAvailable(string scenario, string aircraft, string icao, string mass, string taxiwaysAreInvalid, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("scenario", scenario);
            argumentsOfScenario.Add("aircraft", aircraft);
            argumentsOfScenario.Add("icao", icao);
            argumentsOfScenario.Add("mass", mass);
            argumentsOfScenario.Add("taxiways are invalid", taxiwaysAreInvalid);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check For Invalid Taxiways only when valid data is available", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync(string.Format("that I am an \'{0}\' at \'{1}\' and \'{2}\'", aircraft, icao, mass), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("I ask for taxi", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.ThenAsync(string.Format("If data is valid I want to know what \'{0}\'", taxiwaysAreInvalid), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CheckForInvalidInfrastructreFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CheckForInvalidInfrastructreFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
